(function () {
  'use strict';

  const STORAGE_KEY='workhub-payroll-approved-v1';
  const core=()=>window.WorkHubCore;
  const root=()=>document.getElementById('payroll-root');
  const state={active:'workers',data:null,date:'',weekDate:'',groupFilter:'',workerQuery:'',selectedWorker:'',collapsed:new Set(),bound:false};

  function id(prefix){return `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`;}
  function esc(value){return String(value==null?'':value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));}
  function money(value){return new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',minimumFractionDigits:0,maximumFractionDigits:2}).format(Number(value)||0);}
  function dateLabel(value,options){return new Intl.DateTimeFormat('th-TH',options||{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(core().parseIso(value));}
  function seed(){
    const today=core().todayIso();const dates=core().weekDates(today);
    const data={settings:{defaultOtRate:50},groups:[{id:'grp-permanent',name:'แรงงานประจำ'},{id:'grp-dmr',name:'ไซต์ DMR'},{id:'grp-cr',name:'ไซต์เชียงราย'}],workers:[
      {id:'w1',fullName:'สมชาย ใจดี',nickname:'ชาย',groupId:'grp-dmr',dailyRate:450,otRate:50,effectiveDate:'2026-01-01',status:'ACTIVE',rateHistory:[{effectiveDate:'2026-01-01',dailyRate:450,otRate:50,reason:'ปรับตามผลงาน'},{effectiveDate:'2025-01-01',dailyRate:420,otRate:50,reason:'เริ่มงาน'}]},
      {id:'w2',fullName:'วิทยา กันหา',nickname:'โต้ง',groupId:'grp-dmr',dailyRate:450,otRate:50,effectiveDate:'2026-06-01',status:'ACTIVE',rateHistory:[]},
      {id:'w3',fullName:'ประสิทธิ์ คำมา',nickname:'เอ',groupId:'grp-dmr',dailyRate:420,otRate:50,effectiveDate:'2025-03-15',status:'ACTIVE',rateHistory:[]},
      {id:'w4',fullName:'นครินทร์ สิงห์โต',nickname:'นรินทร์',groupId:'grp-permanent',dailyRate:480,otRate:60,effectiveDate:'2026-01-01',status:'ACTIVE',rateHistory:[]},
      {id:'w5',fullName:'สมหญิง มั่นคง',nickname:'หญิง',groupId:'grp-permanent',dailyRate:420,otRate:50,effectiveDate:'2025-02-01',status:'ACTIVE',rateHistory:[]},
      {id:'w6',fullName:'สุชาติ ดีเลิศ',nickname:'ชาติ',groupId:'grp-cr',dailyRate:400,otRate:50,effectiveDate:'2025-01-01',status:'ACTIVE',rateHistory:[]},
      {id:'w7',fullName:'จำลอง พรมดี',nickname:'ลอง',groupId:'grp-cr',dailyRate:400,otRate:50,effectiveDate:'2025-01-01',status:'ACTIVE',rateHistory:[]},
      {id:'w8',fullName:'อภิชาติ นิลสุข',nickname:'อาร์ต',groupId:'grp-permanent',dailyRate:450,otRate:50,effectiveDate:'2025-04-01',status:'ACTIVE',rateHistory:[]},
    ],attendance:{}};
    dates.forEach((date,dayIndex)=>data.workers.forEach((worker,workerIndex)=>{const absent=(workerIndex+dayIndex)%11===0;data.attendance[`${date}:${worker.id}`]={status:absent?'absent':'present',ot:absent?0:((workerIndex+dayIndex)%5)*.5};}));
    return data;
  }
  function load(){try{state.data=JSON.parse(localStorage.getItem(STORAGE_KEY))||seed();}catch(_){state.data=seed();}state.date=state.date||core().todayIso();state.weekDate=state.weekDate||state.date;state.groupFilter=state.groupFilter||state.data.groups[0]?.id||'';state.selectedWorker=state.selectedWorker||state.data.workers[0]?.id||'';save();}
  function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state.data));}
  function persist(message){save();render();notify(message||'บันทึกในเครื่องแล้ว');}
  function groupName(groupId){return state.data.groups.find(group=>group.id===groupId)?.name||'-';}
  function record(date,workerId){return state.data.attendance[`${date}:${workerId}`]||{status:'',ot:0};}
  function setRecord(date,workerId,changes){const key=`${date}:${workerId}`;state.data.attendance[key]={...record(date,workerId),...changes};if(state.data.attendance[key].status!=='present')state.data.attendance[key].ot=0;}

  function shell(){root().innerHTML=`<div class="module-shell payroll-shell"><div class="module-heading"><div><p class="module-kicker">WORKHUB · PAYROLL</p><h3>สรุปค่าแรง</h3><p>ตั้งค่าคน เช็กชื่อและโอที แล้วตรวจยอดจ่ายรายสัปดาห์</p></div><div class="module-save-state" id="payroll-save-state"><span></span>บันทึกในเครื่องแล้ว</div></div><nav class="module-tabs" aria-label="เมนูสรุปค่าแรง"><button data-payroll-tab="workers">พนักงานและอัตราค่าแรง</button><button data-payroll-tab="daily">เช็กชื่อและโอที</button><button data-payroll-tab="weekly">ตรวจค่าแรงรายสัปดาห์</button></nav><div id="payroll-content"></div><div id="payroll-dialog-host"></div></div>`;bind();render();}
  function render(){root().querySelectorAll('[data-payroll-tab]').forEach(button=>button.classList.toggle('active',button.dataset.payrollTab===state.active));if(state.active==='workers')renderWorkers();if(state.active==='daily')renderDaily();if(state.active==='weekly')renderWeekly();}

  function renderWorkers(){const query=state.workerQuery.trim().toLowerCase();const workers=state.data.workers.filter(worker=>!query||`${worker.fullName} ${worker.nickname} ${groupName(worker.groupId)}`.toLowerCase().includes(query));if(!workers.some(worker=>worker.id===state.selectedWorker))state.selectedWorker=workers[0]?.id||'';const selected=state.data.workers.find(worker=>worker.id===state.selectedWorker);document.getElementById('payroll-content').innerHTML=`<section class="module-panel"><div class="module-toolbar"><div><h4>พนักงานและอัตราค่าแรง</h4><p>อัตราใหม่มีวันที่เริ่มใช้และไม่เปลี่ยนยอดสัปดาห์เก่า</p></div><div class="toolbar-actions"><button class="module-secondary" data-payroll-groups>จัดการกลุ่ม/ไซต์</button><button class="module-secondary" data-ot-setting>ตั้งค่าโอที</button><button class="module-primary" data-worker-add>＋ เพิ่มพนักงาน</button></div></div><label class="module-search"><span>⌕</span><input data-worker-search type="search" value="${esc(state.workerQuery)}" placeholder="ค้นหาชื่อพนักงาน ชื่อเล่น หรือไซต์"></label><div class="worker-layout"><div class="worker-table-wrap"><table class="module-table"><thead><tr><th>ชื่อ–สกุล</th><th>ชื่อเล่น</th><th>กลุ่ม/ไซต์</th><th>ค่าแรง/วัน</th><th>โอที/ชม.</th><th>สถานะ</th></tr></thead><tbody>${workers.length?workers.map(worker=>`<tr class="${worker.id===state.selectedWorker?'selected':''}" data-worker-select="${esc(worker.id)}"><td><strong>${esc(worker.fullName)}</strong></td><td>${esc(worker.nickname)}</td><td>${esc(groupName(worker.groupId))}</td><td>${money(worker.dailyRate)}</td><td>${money(worker.otRate)}</td><td><span class="status-pill">${worker.status==='ACTIVE'?'● ทำงานอยู่':'○ พักงาน'}</span></td></tr>`).join(''):'<tr><td colspan="6"><div class="module-empty">ไม่พบพนักงาน</div></td></tr>'}</tbody></table></div>${selected?workerDetail(selected):'<div class="module-empty">เลือกพนักงานเพื่อดูรายละเอียด</div>'}</div></section>`;}
  function workerDetail(worker){const history=[...(worker.rateHistory||[])].sort((a,b)=>b.effectiveDate.localeCompare(a.effectiveDate));return `<aside class="worker-detail"><div class="worker-avatar">${esc(worker.nickname.slice(0,2)||'WH')}</div><div><span class="status-pill">${worker.status==='ACTIVE'?'● ทำงานอยู่':'○ พักงาน'}</span><h4>${esc(worker.fullName)}</h4><p>${esc(worker.nickname)} · ${esc(groupName(worker.groupId))}</p></div><div class="worker-actions"><button class="module-primary" data-worker-rate="${esc(worker.id)}">ปรับค่าแรง</button><button class="module-secondary" data-worker-edit="${esc(worker.id)}">แก้ไข</button><button class="module-secondary" data-worker-toggle="${esc(worker.id)}">${worker.status==='ACTIVE'?'พักงาน':'กลับเข้าทำงาน'}</button></div><dl class="worker-rate-now"><div><dt>ค่าแรงปัจจุบัน</dt><dd>${money(worker.dailyRate)}/วัน</dd></div><div><dt>โอที</dt><dd>${money(worker.otRate)}/ชม.</dd></div></dl><h5>ประวัติอัตราค่าแรง</h5><ol class="rate-history">${history.length?history.map(item=>`<li><span></span><div><strong>${money(item.dailyRate)}/วัน</strong><small>${money(item.otRate)}/ชม. · เริ่ม ${esc(dateLabel(item.effectiveDate,{day:'numeric',month:'short',year:'numeric'}))}</small><p>${esc(item.reason||'ไม่ระบุเหตุผล')}</p></div></li>`).join(''):'<li class="empty"><span></span><p>ยังไม่มีประวัติการปรับค่าแรง</p></li>'}</ol></aside>`;}
  function workerDialog(worker){const item=worker||{fullName:'',nickname:'',groupId:state.data.groups[0]?.id||'',dailyRate:400,otRate:state.data.settings.defaultOtRate,effectiveDate:core().todayIso(),status:'ACTIVE'};showDialog(`<form method="dialog" data-worker-form data-id="${esc(item.id||'')}" class="wh-form"><div class="wh-dialog__head"><div><span>ข้อมูลพนักงาน</span><h4>${worker?'แก้ไขพนักงาน':'เพิ่มพนักงาน'}</h4></div><button value="cancel">×</button></div><div class="form-grid"><label>ชื่อ–สกุล<input name="fullName" required value="${esc(item.fullName)}"></label><label>ชื่อเล่น<input name="nickname" required value="${esc(item.nickname)}"></label></div><label>กลุ่ม/ไซต์<select name="groupId" required>${state.data.groups.map(group=>`<option value="${esc(group.id)}" ${group.id===item.groupId?'selected':''}>${esc(group.name)}</option>`).join('')}</select></label><div class="form-grid"><label>ค่าแรงต่อวัน<input name="dailyRate" type="number" min="0" step="1" required value="${item.dailyRate}"></label><label>โอทีต่อชั่วโมง<input name="otRate" type="number" min="0" step="1" required value="${item.otRate}"></label></div><label>วันที่เริ่มใช้อัตรา<input name="effectiveDate" type="date" required value="${item.effectiveDate||core().todayIso()}"></label><div class="wh-form__actions"><button value="cancel" class="module-secondary">ยกเลิก</button><button type="submit" class="module-primary">บันทึกพนักงาน</button></div></form>`);}
  function rateDialog(worker){showDialog(`<form method="dialog" data-rate-form data-id="${esc(worker.id)}" class="wh-form"><div class="wh-dialog__head"><div><span>${esc(worker.fullName)}</span><h4>ปรับอัตราค่าแรง</h4></div><button value="cancel">×</button></div><div class="form-grid"><label>ค่าแรงต่อวัน<input name="dailyRate" type="number" min="0" required value="${worker.dailyRate}"></label><label>โอทีต่อชั่วโมง<input name="otRate" type="number" min="0" required value="${worker.otRate}"></label></div><label>วันที่เริ่มใช้<input name="effectiveDate" type="date" required value="${core().todayIso()}"></label><label>เหตุผล<input name="reason" required placeholder="เช่น ปรับตามผลงาน"></label><p class="form-note">ระบบจะสร้างประวัติใหม่ โดยไม่แก้ข้อมูลค่าแรงของวันที่ผ่านมา</p><div class="wh-form__actions"><button value="cancel" class="module-secondary">ยกเลิก</button><button type="submit" class="module-primary">ยืนยันอัตราใหม่</button></div></form>`);}
  function groupDialog(){showDialog(`<form method="dialog" data-payroll-group-form class="wh-form"><div class="wh-dialog__head"><div><span>ตั้งค่า</span><h4>จัดการกลุ่ม/ไซต์</h4></div><button value="cancel">×</button></div><div class="manage-list">${state.data.groups.map(group=>`<div><span>${esc(group.name)}</span><small>${state.data.workers.filter(worker=>worker.groupId===group.id).length} คน</small><button type="button" data-payroll-group-delete="${esc(group.id)}">ลบ</button></div>`).join('')}</div><label>ชื่อกลุ่มหรือไซต์ใหม่<input name="name" required placeholder="เช่น ไซต์งานเชียงราย"></label><div class="wh-form__actions"><button value="cancel" class="module-secondary">ปิด</button><button type="submit" class="module-primary">เพิ่มกลุ่ม/ไซต์</button></div></form>`);}
  function otDialog(){showDialog(`<form method="dialog" data-ot-form class="wh-form"><div class="wh-dialog__head"><div><span>ตั้งค่า</span><h4>อัตราโอทีเริ่มต้น</h4></div><button value="cancel">×</button></div><label>บาทต่อชั่วโมง<input name="defaultOtRate" type="number" min="0" required value="${state.data.settings.defaultOtRate}"></label><p class="form-note">ใช้เป็นค่าเริ่มต้นเมื่อเพิ่มพนักงานใหม่ ปัจจุบัน ${money(state.data.settings.defaultOtRate)} ต่อชั่วโมง</p><div class="wh-form__actions"><button value="cancel" class="module-secondary">ยกเลิก</button><button type="submit" class="module-primary">บันทึกการตั้งค่า</button></div></form>`);}

  function renderDaily(){const totals={present:0,absent:0,ot:0};state.data.workers.filter(worker=>worker.status==='ACTIVE').forEach(worker=>{const item=record(state.date,worker.id);if(item.status==='present')totals.present++;if(item.status==='absent')totals.absent++;totals.ot+=Number(item.ot)||0;});document.getElementById('payroll-content').innerHTML=`<section class="module-panel daily-panel"><div class="module-toolbar"><div><h4>เช็กชื่อและโอทีรายวัน</h4><p>ตั้งค่าทั้งกลุ่มก่อน แล้วแก้เฉพาะคนที่แตกต่าง</p></div><div class="date-stepper"><button data-day-shift="-1" aria-label="วันก่อนหน้า">‹</button><input data-daily-date type="date" value="${state.date}"><button data-day-shift="1" aria-label="วันถัดไป">›</button><button data-day-today>วันนี้</button></div></div><div class="daily-date-label">${esc(dateLabel(state.date))}</div><div class="attendance-groups">${state.data.groups.map(group=>dailyGroup(group)).join('')}</div><div class="daily-sticky"><div><span>มา <strong>${totals.present}</strong></span><span>ไม่มา <strong>${totals.absent}</strong></span><span>โอทีรวม <strong>${totals.ot.toFixed(1)} ชม.</strong></span></div><button class="module-primary" data-save-daily>บันทึกวันนี้</button></div></section>`;}
  function dailyGroup(group){const workers=state.data.workers.filter(worker=>worker.groupId===group.id&&worker.status==='ACTIVE');const collapsed=state.collapsed.has(group.id);return `<article class="attendance-group ${collapsed?'collapsed':''}"><button class="attendance-group__head" data-group-toggle="${esc(group.id)}"><span>${collapsed?'›':'⌄'}</span><strong>${esc(group.name)}</strong><em>${workers.length} คน</em></button><div class="attendance-group__body"><div class="bulk-strip"><div><span>การเข้างานทั้งกลุ่ม</span><div><button data-bulk-status="present" data-group="${esc(group.id)}">มาทั้งกลุ่ม</button><button class="absent" data-bulk-status="absent" data-group="${esc(group.id)}">ไม่มาทั้งกลุ่ม</button><button class="quiet" data-bulk-status="clear" data-group="${esc(group.id)}">ล้าง</button></div></div><div><span>โอทีทั้งกลุ่ม</span><div class="ot-chips">${[0,.5,1,1.5,2,3,4].map(value=>`<button data-bulk-ot="${value}" data-group="${esc(group.id)}">${value===4?'4 ชม.':value}</button>`).join('')}<button data-bulk-ot="custom" data-group="${esc(group.id)}">กำหนดเอง</button></div></div></div><div class="attendance-list">${workers.length?workers.map(worker=>dailyWorker(worker)).join(''):'<div class="module-empty">ยังไม่มีพนักงานในกลุ่มนี้</div>'}</div></div></article>`;}
  function dailyWorker(worker){const item=record(state.date,worker.id);return `<div class="attendance-row"><div class="worker-avatar small">${esc(worker.nickname.slice(0,2))}</div><div class="attendance-name"><strong>${esc(worker.fullName)}</strong><small>${esc(worker.nickname)} · ${money(core().rateAt(worker,state.date,'dailyRate'))}/วัน</small></div><div class="attendance-toggle"><button class="${item.status==='present'?'active present':''}" data-worker-status="present" data-worker="${esc(worker.id)}">มา</button><button class="${item.status==='absent'?'active absent':''}" data-worker-status="absent" data-worker="${esc(worker.id)}">ไม่มา</button></div><div class="ot-stepper"><button data-worker-ot-step="-0.5" data-worker="${esc(worker.id)}" ${item.status!=='present'?'disabled':''}>−</button><output>${Number(item.ot||0).toFixed(1)}</output><button data-worker-ot-step="0.5" data-worker="${esc(worker.id)}" ${item.status!=='present'?'disabled':''}>＋</button><span>ชม.</span></div></div>`;}

  function renderWeekly(){const dates=core().weekDates(state.weekDate);if(!state.data.groups.some(group=>group.id===state.groupFilter))state.groupFilter=state.data.groups[0]?.id||'';const summary=core().weeklyPayroll(state.data.workers.filter(worker=>worker.status==='ACTIVE'),state.data.attendance,dates,state.groupFilter);const labels=['จ.','อ.','พ.','พฤ.','ศ.','ส.','อา.'];document.getElementById('payroll-content').innerHTML=`<section class="module-panel weekly-panel"><div class="module-toolbar"><div><h4>ตรวจค่าแรงรายสัปดาห์</h4><p>${esc(dateLabel(dates[0],{day:'numeric',month:'short',year:'numeric'}))} – ${esc(dateLabel(dates[6],{day:'numeric',month:'short',year:'numeric'}))}</p></div><div class="toolbar-actions"><button class="module-secondary" data-export-pdf>ดาวน์โหลด PDF</button><button class="module-primary" data-export-xlsx>ดาวน์โหลด Excel</button></div></div><div class="weekly-filters"><select data-weekly-group>${state.data.groups.map(group=>`<option value="${esc(group.id)}" ${group.id===state.groupFilter?'selected':''}>${esc(group.name)}</option>`).join('')}</select><div class="date-stepper"><button data-week-shift="-7">สัปดาห์ก่อน</button><button data-week-current>สัปดาห์นี้</button><button data-week-shift="7">สัปดาห์ถัดไป</button></div></div><div class="weekly-table-scroll"><table class="weekly-table"><thead><tr><th>ชื่อพนักงาน</th>${dates.map((date,index)=>`<th><button data-week-day="${date}">${labels[index]}<small>${date.slice(8)}</small></button></th>`).join('')}<th>วันทำงาน</th><th>ค่าแรง</th><th>OT รวม</th><th>ค่าโอที</th><th>ยอดจ่าย</th></tr></thead><tbody>${summary.rows.map(row=>weeklyRow(row)).join('')}</tbody><tfoot><tr><th>รวมทั้งสิ้น</th>${dates.map(date=>{const dayRows=summary.rows.map(row=>row.days.find(item=>item.date===date));return `<td><strong>${dayRows.filter(day=>day.status==='present').length} มา</strong><small>OT ${dayRows.reduce((sum,day)=>sum+day.ot,0).toFixed(1)}</small></td>`;}).join('')}<td>${summary.totals.workDays}</td><td>${money(summary.totals.wages)}</td><td>${summary.totals.otHours.toFixed(1)}</td><td>${money(summary.totals.otPay)}</td><td>${money(summary.totals.total)}</td></tr></tfoot></table></div><p class="table-help">แตะช่องรายวันเพื่อแก้สถานะและโอที หรือแตะหัววันที่เพื่อใช้ค่ากับทุกคนในไซต์</p></section>`;}
  function weeklyRow(row){return `<tr><th><strong>${esc(row.worker.fullName)}</strong><small>${esc(row.worker.nickname)}</small></th>${row.days.map(day=>`<td><button class="day-cell ${day.status==='present'?'present':day.status==='absent'?'absent':''}" data-day-cell="${esc(day.date)}" data-worker="${esc(row.worker.id)}"><strong>${day.status==='present'?'มา':day.status==='absent'?'ขาด':'-'}</strong><small>OT ${day.ot.toFixed(1)}</small></button></td>`).join('')}<td>${row.workDays}</td><td>${money(row.wages)}</td><td>${row.otHours.toFixed(1)}</td><td>${money(row.otPay)}</td><td><strong>${money(row.total)}</strong></td></tr>`;}
  function dayBulkDialog(date){const group=state.data.groups.find(item=>item.id===state.groupFilter);showDialog(`<form method="dialog" data-week-bulk-form data-date="${date}" class="wh-form"><div class="wh-dialog__head"><div><span>${esc(group?.name||'ทุกคน')}</span><h4>ใช้ค่ากับทุกคน · ${esc(dateLabel(date,{weekday:'long',day:'numeric',month:'long'}))}</h4></div><button value="cancel">×</button></div><label>สถานะการมา<select name="status"><option value="present">มาทั้งหมด</option><option value="absent">ไม่มาทั้งหมด</option><option value="">ล้างข้อมูล</option></select></label><label>โอทีทุกคน (ชั่วโมง)<input name="ot" type="number" min="0" max="24" step="0.5" value="2"></label><p class="form-note">การยืนยันจะแทนค่าของทุกคนในกลุ่มสำหรับวันนี้ คุณยังแก้รายบุคคลภายหลังได้</p><div class="wh-form__actions"><button value="cancel" class="module-secondary">ยกเลิก</button><button type="submit" class="module-primary">ใช้กับทุกคน</button></div></form>`);}
  function dayCellDialog(date,worker){const item=record(date,worker.id);showDialog(`<form method="dialog" data-day-cell-form data-date="${date}" data-worker="${esc(worker.id)}" class="wh-form"><div class="wh-dialog__head"><div><span>${esc(worker.fullName)}</span><h4>${esc(dateLabel(date,{weekday:'long',day:'numeric',month:'long'}))}</h4></div><button value="cancel">×</button></div><label>สถานะ<select name="status"><option value="" ${!item.status?'selected':''}>ยังไม่เช็ก</option><option value="present" ${item.status==='present'?'selected':''}>มา</option><option value="absent" ${item.status==='absent'?'selected':''}>ขาด</option></select></label><label>โอที (ชั่วโมง)<input name="ot" type="number" min="0" max="24" step="0.5" value="${Number(item.ot)||0}"></label><div class="wh-form__actions"><button value="cancel" class="module-secondary">ยกเลิก</button><button type="submit" class="module-primary">บันทึกวันนี้</button></div></form>`);}

  function showDialog(html){const host=document.getElementById('payroll-dialog-host');host.innerHTML=`<dialog class="wh-dialog">${html}</dialog>`;const dialog=host.querySelector('dialog');dialog.addEventListener('close',()=>{host.innerHTML='';});dialog.showModal();}
  function closeDialog(){document.querySelector('#payroll-dialog-host dialog')?.close();}
  function notify(message){const status=document.getElementById('payroll-save-state');if(!status)return;status.innerHTML=`<span></span>${esc(message)}`;status.classList.add('flash');setTimeout(()=>status.classList.remove('flash'),1000);}

  function bind(){if(state.bound)return;state.bound=true;root().addEventListener('input',event=>{if(event.target.matches('[data-worker-search]')){state.workerQuery=event.target.value;renderWorkers();}});root().addEventListener('change',event=>{if(event.target.matches('[data-daily-date]')){state.date=event.target.value;renderDaily();}if(event.target.matches('[data-weekly-group]')){state.groupFilter=event.target.value;renderWeekly();}});root().addEventListener('click',event=>{
    const tab=event.target.closest('[data-payroll-tab]');if(tab){state.active=tab.dataset.payrollTab;render();return;}
    if(event.target.closest('[data-worker-add]'))return workerDialog();const workerSelect=event.target.closest('[data-worker-select]');if(workerSelect){state.selectedWorker=workerSelect.dataset.workerSelect;renderWorkers();return;}const workerEdit=event.target.closest('[data-worker-edit]');if(workerEdit)return workerDialog(state.data.workers.find(worker=>worker.id===workerEdit.dataset.workerEdit));const workerRate=event.target.closest('[data-worker-rate]');if(workerRate)return rateDialog(state.data.workers.find(worker=>worker.id===workerRate.dataset.workerRate));const workerToggle=event.target.closest('[data-worker-toggle]');if(workerToggle){const worker=state.data.workers.find(item=>item.id===workerToggle.dataset.workerToggle);worker.status=worker.status==='ACTIVE'?'PAUSED':'ACTIVE';persist(worker.status==='ACTIVE'?'เปิดใช้งานพนักงานแล้ว':'พักงานพนักงานแล้ว');return;}if(event.target.closest('[data-payroll-groups]'))return groupDialog();if(event.target.closest('[data-ot-setting]'))return otDialog();const groupDelete=event.target.closest('[data-payroll-group-delete]');if(groupDelete){if(state.data.workers.some(worker=>worker.groupId===groupDelete.dataset.payrollGroupDelete))return alert('ลบกลุ่มไม่ได้ เพราะยังมีพนักงานอยู่ในกลุ่ม');state.data.groups=state.data.groups.filter(group=>group.id!==groupDelete.dataset.payrollGroupDelete);closeDialog();persist('ลบกลุ่มแล้ว');return;}
    const groupToggle=event.target.closest('[data-group-toggle]');if(groupToggle){state.collapsed.has(groupToggle.dataset.groupToggle)?state.collapsed.delete(groupToggle.dataset.groupToggle):state.collapsed.add(groupToggle.dataset.groupToggle);renderDaily();return;}const dayShift=event.target.closest('[data-day-shift]');if(dayShift){state.date=core().addDays(state.date,Number(dayShift.dataset.dayShift));renderDaily();return;}if(event.target.closest('[data-day-today]')){state.date=core().todayIso();renderDaily();return;}const bulkStatus=event.target.closest('[data-bulk-status]');if(bulkStatus){const workers=state.data.workers.filter(worker=>worker.groupId===bulkStatus.dataset.group&&worker.status==='ACTIVE');workers.forEach(worker=>bulkStatus.dataset.bulkStatus==='clear'?delete state.data.attendance[`${state.date}:${worker.id}`]:setRecord(state.date,worker.id,{status:bulkStatus.dataset.bulkStatus,ot:0}));persist('ใช้สถานะกับทั้งกลุ่มแล้ว');return;}const bulkOt=event.target.closest('[data-bulk-ot]');if(bulkOt){let value=bulkOt.dataset.bulkOt;if(value==='custom'){value=prompt('กรอกชั่วโมงโอที ใช้ทศนิยม .5 ได้','5');if(value==null)return;}value=core().roundHalf(core().clamp(value,0,24));state.data.workers.filter(worker=>worker.groupId===bulkOt.dataset.group&&worker.status==='ACTIVE').forEach(worker=>setRecord(state.date,worker.id,{status:'present',ot:value}));persist(`ใช้โอที ${value} ชั่วโมงกับทั้งกลุ่มแล้ว`);return;}const workerStatus=event.target.closest('[data-worker-status]');if(workerStatus){setRecord(state.date,workerStatus.dataset.worker,{status:workerStatus.dataset.workerStatus});persist('แก้สถานะรายบุคคลแล้ว');return;}const workerOt=event.target.closest('[data-worker-ot-step]');if(workerOt){const item=record(state.date,workerOt.dataset.worker);setRecord(state.date,workerOt.dataset.worker,{status:'present',ot:core().clamp(core().roundHalf(Number(item.ot)+Number(workerOt.dataset.workerOtStep)),0,24)});persist('แก้โอทีรายบุคคลแล้ว');return;}if(event.target.closest('[data-save-daily]')){save();notify('บันทึกข้อมูลวันนี้แล้ว');return;}
    const weekShift=event.target.closest('[data-week-shift]');if(weekShift){state.weekDate=core().addDays(state.weekDate,Number(weekShift.dataset.weekShift));renderWeekly();return;}if(event.target.closest('[data-week-current]')){state.weekDate=core().todayIso();renderWeekly();return;}const weekDay=event.target.closest('[data-week-day]');if(weekDay)return dayBulkDialog(weekDay.dataset.weekDay);const dayCell=event.target.closest('[data-day-cell]');if(dayCell)return dayCellDialog(dayCell.dataset.dayCell,state.data.workers.find(worker=>worker.id===dayCell.dataset.worker));if(event.target.closest('[data-export-pdf]'))return exportPdf();if(event.target.closest('[data-export-xlsx]'))return exportXlsx();
  });root().addEventListener('submit',event=>{event.preventDefault();const form=event.target;const values=Object.fromEntries(new FormData(form));if(form.matches('[data-worker-form]')){const existing=state.data.workers.find(worker=>worker.id===form.dataset.id);const changed=existing&&(Number(values.dailyRate)!==Number(existing.dailyRate)||Number(values.otRate)!==Number(existing.otRate));const item={...(existing||{}),id:existing?.id||id('worker'),fullName:values.fullName.trim(),nickname:values.nickname.trim(),groupId:values.groupId,dailyRate:Number(values.dailyRate),otRate:Number(values.otRate),effectiveDate:values.effectiveDate,status:existing?.status||'ACTIVE',rateHistory:existing?.rateHistory||[]};if(changed)item.rateHistory.push({effectiveDate:values.effectiveDate,dailyRate:item.dailyRate,otRate:item.otRate,reason:'แก้ไขข้อมูลพนักงาน'});state.data.workers=existing?state.data.workers.map(worker=>worker.id===item.id?item:worker):[item,...state.data.workers];state.selectedWorker=item.id;closeDialog();persist('บันทึกพนักงานแล้ว');}if(form.matches('[data-rate-form]')){const worker=state.data.workers.find(item=>item.id===form.dataset.id);worker.dailyRate=Number(values.dailyRate);worker.otRate=Number(values.otRate);worker.effectiveDate=values.effectiveDate;worker.rateHistory=worker.rateHistory||[];worker.rateHistory.push({effectiveDate:values.effectiveDate,dailyRate:worker.dailyRate,otRate:worker.otRate,reason:values.reason.trim()});closeDialog();persist('บันทึกอัตราใหม่แล้ว');}if(form.matches('[data-payroll-group-form]')){const name=values.name.trim();if(state.data.groups.some(group=>group.name.toLowerCase()===name.toLowerCase()))return alert('มีกลุ่มชื่อนี้แล้ว');state.data.groups.push({id:id('group'),name});closeDialog();persist('เพิ่มกลุ่ม/ไซต์แล้ว');}if(form.matches('[data-ot-form]')){state.data.settings.defaultOtRate=Number(values.defaultOtRate);closeDialog();persist('บันทึกอัตราโอทีเริ่มต้นแล้ว');}if(form.matches('[data-week-bulk-form]')){state.data.workers.filter(worker=>worker.groupId===state.groupFilter&&worker.status==='ACTIVE').forEach(worker=>values.status?setRecord(form.dataset.date,worker.id,{status:values.status,ot:values.status==='present'?core().roundHalf(values.ot):0}):delete state.data.attendance[`${form.dataset.date}:${worker.id}`]);closeDialog();persist('ใช้ค่ากับทุกคนในไซต์แล้ว');}if(form.matches('[data-day-cell-form]')){setRecord(form.dataset.date,form.dataset.worker,{status:values.status,ot:values.status==='present'?core().roundHalf(values.ot):0});closeDialog();persist('แก้ข้อมูลรายวันแล้ว');}});}

  function exportPdf(){const dates=core().weekDates(state.weekDate);const group=state.data.groups.find(item=>item.id===state.groupFilter);const summary=core().weeklyPayroll(state.data.workers.filter(worker=>worker.status==='ACTIVE'),state.data.attendance,dates,state.groupFilter);const popup=window.open('','_blank');if(!popup)return alert('เบราว์เซอร์บล็อกหน้ารายงาน กรุณาอนุญาต Pop-up แล้วลองใหม่');popup.document.write(`<!doctype html><html lang="th"><head><meta charset="utf-8"><title>สรุปค่าแรง ${esc(group?.name||'')}</title><style>body{font-family:"Noto Sans Thai",sans-serif;color:#2d211c;padding:28px}h1{margin:0}p{color:#6b5a50}table{width:100%;border-collapse:collapse;margin-top:20px;font-size:12px}th,td{border:1px solid #cdbbab;padding:7px;text-align:right}th:first-child,td:first-child{text-align:left}thead{background:#2d211c;color:white}tfoot{font-weight:bold;background:#f4e8dc}@media print{button{display:none}}</style></head><body><h1>สรุปค่าแรงรายสัปดาห์</h1><p>${esc(group?.name||'')} · ${esc(dateLabel(dates[0]))} – ${esc(dateLabel(dates[6]))}</p><table><thead><tr><th>ชื่อ–สกุล</th><th>วันทำงาน</th><th>ค่าแรง</th><th>OT (ชม.)</th><th>ค่าโอที</th><th>ยอดจ่าย</th></tr></thead><tbody>${summary.rows.map(row=>`<tr><td>${esc(row.worker.fullName)}</td><td>${row.workDays}</td><td>${money(row.wages)}</td><td>${row.otHours.toFixed(1)}</td><td>${money(row.otPay)}</td><td>${money(row.total)}</td></tr>`).join('')}</tbody><tfoot><tr><td>รวม</td><td>${summary.totals.workDays}</td><td>${money(summary.totals.wages)}</td><td>${summary.totals.otHours.toFixed(1)}</td><td>${money(summary.totals.otPay)}</td><td>${money(summary.totals.total)}</td></tr></tfoot></table><script>onload=()=>setTimeout(()=>print(),250)<\/script></body></html>`);popup.document.close();}
  async function exportXlsx(){if(!window.JSZip)return alert('ระบบสร้าง Excel ยังไม่พร้อม กรุณารีโหลดหน้า');const dates=core().weekDates(state.weekDate);const zip=new JSZip();const groups=state.data.groups;const sheets=[];groups.forEach((group,index)=>{const summary=core().weeklyPayroll(state.data.workers.filter(worker=>worker.status==='ACTIVE'),state.data.attendance,dates,group.id);const rows=[['ชื่อ–สกุล','ชื่อเล่น',...dates.map(date=>date),'วันทำงาน','ค่าแรง','OT รวม','ค่าโอที','ยอดจ่าย'],...summary.rows.map(row=>[row.worker.fullName,row.worker.nickname,...row.days.map(day=>`${day.status==='present'?'มา':day.status==='absent'?'ขาด':'-'} / OT ${day.ot}`),row.workDays,row.wages,row.otHours,row.otPay,row.total]),['รวม','','','','','','','','',summary.totals.workDays,summary.totals.wages,summary.totals.otHours,summary.totals.otPay,summary.totals.total]];sheets.push({name:group.name.slice(0,31),xml:sheetXml(rows),index:index+1});});zip.file('[Content_Types].xml',contentTypes(sheets.length));zip.folder('_rels').file('.rels','<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');const xl=zip.folder('xl');xl.file('workbook.xml',`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map(sheet=>`<sheet name="${xml(sheet.name)}" sheetId="${sheet.index}" r:id="rId${sheet.index}"/>`).join('')}</sheets></workbook>`);xl.folder('_rels').file('workbook.xml.rels',`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map(sheet=>`<Relationship Id="rId${sheet.index}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${sheet.index}.xml"/>`).join('')}</Relationships>`);const ws=xl.folder('worksheets');sheets.forEach(sheet=>ws.file(`sheet${sheet.index}.xml`,sheet.xml));const blob=await zip.generateAsync({type:'blob',mimeType:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'});downloadBlob(blob,`workhub-payroll-${dates[0]}-${dates[6]}.xlsx`);notify('สร้าง Excel แยกตามไซต์แล้ว');}
  function xml(value){return String(value==null?'':value).replace(/[<>&'\"]/g,char=>({'<':'&lt;','>':'&gt;','&':'&amp;',"'":'&apos;','"':'&quot;'}[char]));}
  function col(index){let value='';for(let n=index+1;n;n=Math.floor((n-1)/26))value=String.fromCharCode(65+(n-1)%26)+value;return value;}
  function sheetXml(rows){return `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetData>${rows.map((row,r)=>`<row r="${r+1}">${row.map((value,c)=>typeof value==='number'?`<c r="${col(c)}${r+1}" t="n"><v>${value}</v></c>`:`<c r="${col(c)}${r+1}" t="inlineStr"><is><t>${xml(value)}</t></is></c>`).join('')}</row>`).join('')}</sheetData></worksheet>`;}
  function contentTypes(count){return `<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${Array.from({length:count},(_,index)=>`<Override PartName="/xl/worksheets/sheet${index+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`;}
  function downloadBlob(blob,name){const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}

  function activate(force){if(!state.data||force)load();if(!root().querySelector('.module-shell')||force)shell();else render();}
  window.PayrollModule=Object.freeze({activate,resetLocal:()=>{localStorage.removeItem(STORAGE_KEY);state.data=null;activate(true);}});
})();
