import { config } from './config.mjs';
import { lineQueueWarnings } from './line-queue.mjs';
import { execute, one, ping, select, transaction } from './db.mjs';
import { readBuffer, storeBuffer } from './files.mjs';
import { openApiSession, openProtectedSession, requireApiSession, requireProtectedSession } from './auth.mjs';
import { apiError, clean, envelope, nowSql, publicRow, token, uuid } from './utils.mjs';
import * as masters from './actions/masters.mjs';
import * as bills from './actions/bills.mjs';
import * as receipts from './actions/receipts.mjs';
import * as modules from './actions/modules.mjs';
import * as line from './line.mjs';

const protectedActions = new Set([
  'getReceiptWorkspace','saveReceiptTemplate','downloadReceiptTemplate','deleteReceiptTemplate','saveLaborGroup','createReceiptBatch','queueReceiptCard','processReceiptBatchAI','retryReceiptRegistration','getReceiptCardPreview','deleteReceiptRegistration','cancelReceiptBatch','saveReceiptCardDraft','saveReceiptRegistrations','saveReceiptExportOption','saveReceiptRegistrationEntry','listReceiptRegistrations','previewReceiptExport','exportReceiptDocuments','exportReceiptRosterExcel','getPayrollRegistry','savePayrollWorker','setLaborGroupActive','deletePayrollWorker','getAiUsageSummary','saveAiQuotaSettings','getModuleState','saveModuleState','getModuleFile','saveModuleFile','deleteModuleFile','listModuleSnapshots','restoreModuleSnapshot',
]);
const mutationActions = new Set([
  'submitBillPages','retryBillAiJob','updateBill','confirmBill','deleteBill','restoreBill','saveMasterData','deleteMasterData','saveBillOwnerName','saveQuickSettings','clearQuickSettings','backfillLineUsernames','saveReceiptTemplate','deleteReceiptTemplate','saveLaborGroup','createReceiptBatch','queueReceiptCard','processReceiptBatchAI','retryReceiptRegistration','deleteReceiptRegistration','cancelReceiptBatch','saveReceiptCardDraft','saveReceiptRegistrations','saveReceiptExportOption','saveReceiptRegistrationEntry','exportReceiptDocuments','exportReceiptRosterExcel','savePayrollWorker','setLaborGroupActive','deletePayrollWorker','saveAiQuotaSettings','saveModuleState','saveModuleFile','deleteModuleFile','restoreModuleSnapshot',
]);

async function reserveMutation(requestId, action, deviceId) {
  const id=clean(requestId,160);
  if(!/^[A-Za-z0-9_-]{16,160}$/.test(id))throw apiError('INVALID_REQUEST_ID','Request ID ไม่ถูกต้อง');
  return transaction(async connection=>{
    const[insert]=await connection.execute("INSERT IGNORE INTO mutation_log (mutation_id,action,actor,status,result_json,created_at) VALUES (?,?,?,'PROCESSING',NULL,?)",[id,action,deviceId,nowSql()]);
    if(insert.affectedRows===1)return{completed:false};
    const[rows]=await connection.execute('SELECT * FROM mutation_log WHERE mutation_id=? FOR UPDATE',[id]);const row=rows[0];
    if(row?.status==='SUCCEEDED'&&row.result_json)return{completed:true,data:JSON.parse(row.result_json)};
    const age=Date.now()-new Date(String(row?.created_at).replace(' ','T')+'Z').getTime();
    if(row?.status==='PROCESSING'&&age<8*60*1000)throw apiError('MUTATION_IN_PROGRESS','รายการเดิมกำลังประมวลผล กรุณารอสักครู่แล้วลองอีกครั้ง',409);
    await connection.execute("UPDATE mutation_log SET action=?,actor=?,status='PROCESSING',result_json=NULL,created_at=?,completed_at=NULL WHERE mutation_id=?",[action,deviceId,nowSql(),id]);
    return{completed:false};
  });
}

async function finishMutation(requestId,data){await execute("UPDATE mutation_log SET status='SUCCEEDED',result_json=:result,completed_at=:completed WHERE mutation_id=:id",{id:requestId,result:JSON.stringify(data),completed:nowSql()});}
async function failMutation(requestId,error){await execute("UPDATE mutation_log SET status='FAILED',result_json=:result,completed_at=:completed WHERE mutation_id=:id",{id:requestId,result:JSON.stringify({message:clean(error.message,500)}),completed:nowSql()});}

async function createExportTicket(buffer,fileName,mimeType,count,metadata,deviceId){const stored=await storeBuffer('exports',fileName,buffer);const downloadToken=token(48),expires=new Date(Date.now()+6*60*60*1000);await execute('INSERT INTO export_tickets (ticket,file_path,file_name,mime_type,size_bytes,device_id,expires_at,created_at) VALUES (:ticket,:path,:name,:mime,:size,:device,:expires,:created)',{ticket:downloadToken,path:stored.relative,name:fileName,mime:mimeType,size:buffer.length,device:deviceId,expires,created:nowSql()});if(metadata?.format){const rows=metadata.rows||[],payload=metadata.payload||{};await execute('INSERT INTO generated_documents (generated_id,format,template_id,group_ids,registration_ids,person_count,file_path,file_name,created_by,created_at) VALUES (:id,:format,:template,:groups,:registrations,:count,:path,:name,:actor,:created)',{id:uuid(),format:metadata.format,template:metadata.templateId||'',groups:JSON.stringify(payload.group_ids||[]),registrations:JSON.stringify(rows.map(row=>row.registration_id)),count:rows.length,path:stored.relative,name:fileName,actor:clean(payload.created_by||'WEB',160),created:nowSql()});}return{fileId:'',fileName,mimeType,count:Number(count)||0,sizeBytes:buffer.length,downloadToken,driveUrl:'',delivery:'chunked'};}

async function getExportFileChunk(downloadToken,offset,deviceId){const ticketValue=clean(downloadToken,96);if(!/^[A-Za-z0-9_-]{40,96}$/.test(ticketValue))throw apiError('INVALID_DOWNLOAD_TOKEN','รหัสดาวน์โหลดไม่ถูกต้อง');const ticketRow=await one('SELECT * FROM export_tickets WHERE ticket=:ticket AND device_id=:device',{ticket:ticketValue,device:deviceId});if(!ticketRow||new Date(String(ticketRow.expires_at).replace(' ','T')+'Z').getTime()<=Date.now())throw apiError('DOWNLOAD_EXPIRED','ลิงก์ดาวน์โหลดหมดอายุ กรุณาสร้างไฟล์ใหม่',410);const start=Math.trunc(Number(offset)||0),size=Number(ticketRow.size_bytes);if(start<0||start>size)throw apiError('INVALID_OFFSET','ตำแหน่งข้อมูลดาวน์โหลดไม่ถูกต้อง');if(start===size)return{offset:start,nextOffset:start,totalBytes:size,base64:'',done:true};const buffer=await readBuffer(ticketRow.file_path),end=Math.min(size,start+1024*1024),chunk=buffer.subarray(start,end);return{offset:start,nextOffset:end,totalBytes:size,base64:chunk.toString('base64'),done:end>=size};}

async function getSystemStatus(){const database=await ping();const queueWarnings=await lineQueueWarnings();const lineConfigured=!!(config.lineChannelSecret&&config.lineChannelAccessToken&&config.publicBaseUrl);return{spreadsheet:`MariaDB ${database.version}`,folder:config.dataDir,folderUrl:'',geminiConfigured:!!config.geminiApiKey,receiptGeminiConfigured:!!config.receiptGeminiApiKey,lineConfigured,model:config.geminiModel,receiptModel:config.receiptGeminiModel,version:config.appVersion,frontendUrl:config.publicBaseUrl,lineDiagnostics:{webhook:{endpoint:config.publicBaseUrl?`${config.publicBaseUrl}/webhook/line`:''},liff_url:'',android_external_url:config.publicBaseUrl,rich_menus:[],warnings:lineConfigured?queueWarnings:['กรุณาตั้งค่า PUBLIC_BASE_URL, LINE_CHANNEL_SECRET และ LINE_CHANNEL_ACCESS_TOKEN บน NAS']},geminiDiagnostics:{message:config.geminiApiKey?'ตั้งค่าแล้ว (ใช้เฉพาะส่วนบิล)':'ยังไม่ได้ตั้งค่า GEMINI_API_KEY',valid:!!config.geminiApiKey},receiptGeminiDiagnostics:{message:config.receiptGeminiApiKey?'ตั้งค่าแล้ว (ใช้เฉพาะเอกสารใบรับเงิน)':'ยังไม่ได้ตั้งค่า RECEIPT_GEMINI_API_KEY',valid:!!config.receiptGeminiApiKey},storage:{provider:'Synology NAS',dataDir:config.dataDir},database:{name:database.database_name,version:database.version}};}

function pacificDayWindow(){
  const now=new Date(),parts=Object.fromEntries(new Intl.DateTimeFormat('en-CA',{timeZone:'America/Los_Angeles',year:'numeric',month:'2-digit',day:'2-digit',timeZoneName:'longOffset'}).formatToParts(now).map(part=>[part.type,part.value]));
  const offset=(parts.timeZoneName||'GMT-08:00').replace('GMT','')||'-08:00',ymd=`${parts.year}-${parts.month}-${parts.day}`;
  const start=new Date(`${ymd}T00:00:00${offset}`),end=new Date(start.getTime()+24*60*60*1000);
  return{start,end,resetAt:end.toISOString(),label:ymd};
}

async function getAiUsageSummary(){
  const window=pacificDayWindow(),scopeSql="CASE WHEN bill_id LIKE 'receipt:%' THEN 'RECEIPTS' ELSE 'BILLS' END";
  const [today,settings,trend,errors]=await Promise.all([
    select(`SELECT ${scopeSql} AS scope_key,COUNT(*) AS requests,SUM(success) AS successful,SUM(total_tokens) AS total_tokens,SUM(input_tokens) AS input_tokens,SUM(output_tokens) AS output_tokens,SUM(thought_tokens) AS thought_tokens,ROUND(AVG(latency_ms)) AS avg_latency_ms FROM ai_usage WHERE created_at>=:start AND created_at<:end GROUP BY scope_key`,{start:window.start,end:window.end}),
    select('SELECT * FROM ai_quota_settings ORDER BY scope_key'),
    select(`SELECT DATE(created_at) AS usage_date,${scopeSql} AS scope_key,COUNT(*) AS requests,SUM(total_tokens) AS total_tokens,SUM(success) AS successful FROM ai_usage WHERE created_at>=DATE_SUB(UTC_TIMESTAMP(),INTERVAL 13 DAY) GROUP BY DATE(created_at),scope_key ORDER BY usage_date,scope_key`),
    select(`SELECT ${scopeSql} AS scope_key,model,error,created_at FROM ai_usage WHERE success=0 ORDER BY created_at DESC LIMIT 8`),
  ]);
  const usageMap=new Map(today.map(row=>[row.scope_key,row])),settingMap=new Map(settings.map(row=>[row.scope_key,row]));
  const scopes=[{scope_key:'BILLS',label:'ตรวจบิล',model:config.geminiModel,configured:!!config.geminiApiKey},{scope_key:'RECEIPTS',label:'เอกสารใบรับเงิน',model:config.receiptGeminiModel,configured:!!config.receiptGeminiApiKey}].map(scope=>{
    const usage=usageMap.get(scope.scope_key)||{},setting=settingMap.get(scope.scope_key)||{};
    const requests=Number(usage.requests)||0,tokens=Number(usage.total_tokens)||0,requestLimit=Number(setting.request_limit_day)||0,tokenLimit=Number(setting.token_limit_day)||0;
    return{...scope,plan_name:setting.plan_name||'FREE',requests,successful:Number(usage.successful)||0,failed:Math.max(0,requests-(Number(usage.successful)||0)),input_tokens:Number(usage.input_tokens)||0,output_tokens:Number(usage.output_tokens)||0,thought_tokens:Number(usage.thought_tokens)||0,total_tokens:tokens,avg_latency_ms:Number(usage.avg_latency_ms)||0,request_limit_day:requestLimit,token_limit_day:tokenLimit,requests_remaining:requestLimit?Math.max(0,requestLimit-requests):null,tokens_remaining:tokenLimit?Math.max(0,tokenLimit-tokens):null,request_percent:requestLimit?Math.min(100,requests/requestLimit*100):null,token_percent:tokenLimit?Math.min(100,tokens/tokenLimit*100):null};
  });
  return{plan:'FREE',day_label:window.label,reset_at:window.resetAt,time_zone:'America/Los_Angeles',scopes,trend:trend.map(publicRow),errors:errors.map(publicRow),note:'นับเฉพาะคำขอที่ส่งจาก WorkHub โควตาจริงใช้ร่วมกันระดับ Google Cloud project และ model'};
}

async function saveAiQuotaSettings(payload={}){
  const rows=Array.isArray(payload.scopes)?payload.scopes:[];
  for(const row of rows){const scope=clean(row.scope_key,32).toUpperCase();if(!['BILLS','RECEIPTS'].includes(scope))continue;const requests=Math.max(0,Math.trunc(Number(row.request_limit_day)||0)),tokens=Math.max(0,Math.trunc(Number(row.token_limit_day)||0));await execute("INSERT INTO ai_quota_settings (scope_key,plan_name,request_limit_day,token_limit_day,updated_at) VALUES (:scope,'FREE',:requests,:tokens,:updated) ON DUPLICATE KEY UPDATE plan_name='FREE',request_limit_day=VALUES(request_limit_day),token_limit_day=VALUES(token_limit_day),updated_at=VALUES(updated_at)",{scope,requests,tokens,updated:nowSql()});}
  return getAiUsageSummary();
}

async function actionHandler(action,args,session){const createTicket=(buffer,fileName,mimeType,count,metadata)=>createExportTicket(buffer,fileName,mimeType,count,metadata,session.deviceId);const handlers={
  getBootstrapData:()=>masters.getBootstrapData(args[0]),getDashboard:()=>masters.getDashboard(args[0]),getBillOwners:()=>masters.listBillOwners(),listBills:()=>masters.listBills(args[0]),listPendingReviewBills:()=>masters.listPendingReviewBills(),getQuickSettings:()=>masters.getQuickSettings(),saveQuickSettings:()=>masters.saveQuickSettings(args[0]),clearQuickSettings:()=>masters.clearQuickSettings(args[0]),saveMasterData:()=>masters.saveMasterData(args[0],args[1],session.deviceId),deleteMasterData:()=>masters.deleteMasterData(args[0],args[1],session.deviceId),saveBillOwnerName:()=>masters.saveBillOwnerName(args[0],session.deviceId),
  submitBillPages:()=>bills.submitBillPages(args[0]),getBillAiJob:()=>bills.getBillAiJob(args[0]),listBillAiJobs:()=>bills.listBillAiJobs(args[0]),retryBillAiJob:()=>bills.retryBillAiJob(args[0]),getBillDetail:()=>bills.getBillDetail(args[0]),getBillDocumentPreview:()=>bills.getBillDocumentPreview(args[0]),updateBill:()=>bills.updateBill(args[0],session.deviceId),confirmBill:()=>bills.confirmBill(args[0],args[1]||session.deviceId),deleteBill:()=>bills.deleteBill(args[0],args[1]||session.deviceId),restoreBill:()=>bills.restoreBill(args[0],args[1]||session.deviceId),exportMonthlyBillWord:()=>bills.exportMonthlyBillWord(args[0],createTicket),exportMonthlyBillExcel:()=>bills.exportMonthlyBillExcel(args[0],createTicket),backfillLineUsernames:()=>line.backfillLineUsernames(),
  getReceiptWorkspace:()=>receipts.getReceiptWorkspace(args[0]),saveReceiptTemplate:()=>receipts.saveReceiptTemplate(args[0]),downloadReceiptTemplate:()=>receipts.downloadReceiptTemplate(args[0],createTicket),deleteReceiptTemplate:()=>receipts.deleteReceiptTemplate(args[0]),saveLaborGroup:()=>receipts.saveLaborGroup(args[0]),createReceiptBatch:()=>receipts.createReceiptBatch(args[0]),queueReceiptCard:()=>receipts.queueReceiptCard(args[0]),processReceiptBatchAI:()=>receipts.processReceiptBatchAI(args[0]),retryReceiptRegistration:()=>receipts.retryReceiptRegistration(args[0]),getReceiptCardPreview:()=>receipts.getReceiptCardPreview(args[0]),deleteReceiptRegistration:()=>receipts.deleteReceiptRegistration(args[0]),cancelReceiptBatch:()=>receipts.cancelReceiptBatch(args[0]),saveReceiptCardDraft:()=>receipts.saveReceiptCardDraft(args[0]),saveReceiptRegistrations:()=>receipts.saveReceiptRegistrations(args[0]),saveReceiptExportOption:()=>receipts.saveReceiptExportOption(args[0]),saveReceiptRegistrationEntry:()=>receipts.saveReceiptRegistrationEntry(args[0]),listReceiptRegistrations:()=>receipts.listReceiptRegistrations(args[0]),previewReceiptExport:()=>receipts.previewReceiptExport(args[0]),exportReceiptDocuments:()=>receipts.exportReceiptDocuments(args[0],createTicket),exportReceiptRosterExcel:()=>receipts.exportReceiptRosterExcel(args[0],createTicket),getPayrollRegistry:()=>receipts.getPayrollRegistry(),savePayrollWorker:()=>receipts.savePayrollWorker(args[0]),setLaborGroupActive:()=>receipts.setLaborGroupActive(args[0]),deletePayrollWorker:()=>receipts.deletePayrollWorker(args[0]),
  getExportFileChunk:()=>getExportFileChunk(args[0],args[1],session.deviceId),getSystemStatus:()=>getSystemStatus(),getAiUsageSummary:()=>getAiUsageSummary(),saveAiQuotaSettings:()=>saveAiQuotaSettings(args[0]),
  getModuleState:()=>modules.getModuleState(args[0],session.deviceId),saveModuleState:()=>modules.saveModuleState(args[0],session.deviceId),getModuleFile:()=>modules.getModuleFile(args[0]),saveModuleFile:()=>modules.saveModuleFile(args[0],session.deviceId),deleteModuleFile:()=>modules.deleteModuleFile(args[0]),listModuleSnapshots:()=>modules.listModuleSnapshots(args[0]),restoreModuleSnapshot:()=>modules.restoreModuleSnapshot(args[0],session.deviceId),
};if(!handlers[action])throw apiError('ACTION_NOT_ALLOWED','คำสั่งนี้ไม่ได้รับอนุญาต',404);return handlers[action]();}

export async function handleApi(body={}){const requestId=clean(body.requestId,160)||uuid();if(clean(body.apiVersion,20)!==config.apiVersion)throw apiError('API_VERSION_MISMATCH','เวอร์ชันหน้าเว็บไม่ตรงกับ Backend กรุณารีโหลด');const action=clean(body.action,80),args=Array.isArray(body.args)?body.args:[];if(action==='health')return envelope(true,{appName:config.appName,appVersion:config.appVersion,apiVersion:config.apiVersion,schemaVersion:config.schemaVersion,serverTime:new Date().toISOString(),accessMode:'OPEN',loginRequired:false,sessionRequired:false,pinMustChange:false,liffId:'',frontendUrl:'',protectedAccess:{configured:!!config.passwordHash,sessionSeconds:config.protectedSessionSeconds},modules:{expenses:true,receipts:!!config.passwordHash,payroll:true,tasks:true,reports:true,dailyReports:true}},null,requestId,config.apiVersion);if(action==='openSession')return envelope(true,await openApiSession(args[0]),null,requestId,config.apiVersion);const session=await requireApiSession(body.sessionToken);if(action==='openProtectedSession')return envelope(true,await openProtectedSession(args[0],session.deviceId),null,requestId,config.apiVersion);if(protectedActions.has(action))await requireProtectedSession(body.protectedToken,session.deviceId);const mutation=mutationActions.has(action);if(mutation){const reservation=await reserveMutation(requestId,action,session.deviceId);if(reservation.completed)return envelope(true,reservation.data,null,requestId,config.apiVersion);}try{const data=await actionHandler(action,args,session);if(mutation)await finishMutation(requestId,data);return envelope(true,data,null,requestId,config.apiVersion);}catch(error){if(mutation)await failMutation(requestId,error);throw error;}}

export function apiErrorEnvelope(error,requestId){return envelope(false,null,{code:clean(error.code||'SERVER_ERROR',80),message:clean(error.message||error,500)},requestId,config.apiVersion);}
