import { config } from './config.mjs';
import { execute, one, ping, select, transaction } from './db.mjs';
import { readBuffer, storeBuffer } from './files.mjs';
import { openApiSession, openProtectedSession, requireApiSession, requireProtectedSession } from './auth.mjs';
import { apiError, clean, envelope, nowSql, publicRow, token, uuid } from './utils.mjs';
import * as masters from './actions/masters.mjs';
import * as bills from './actions/bills.mjs';
import * as receipts from './actions/receipts.mjs';
import * as line from './line.mjs';

const protectedActions = new Set([
  'getReceiptWorkspace','saveReceiptTemplate','saveLaborGroup','createReceiptBatch','saveReceiptCardDraft','saveReceiptRegistrations','listReceiptRegistrations','previewReceiptExport','exportReceiptDocuments','exportReceiptRosterExcel','verifyDatabaseAccess',
]);
const mutationActions = new Set([
  'submitBillPages','updateBill','confirmBill','deleteBill','restoreBill','saveMasterData','deleteMasterData','saveQuickSettings','clearQuickSettings','backfillLineUsernames','saveReceiptTemplate','saveLaborGroup','createReceiptBatch','saveReceiptCardDraft','saveReceiptRegistrations','exportReceiptDocuments','exportReceiptRosterExcel',
]);

async function reserveMutation(requestId, action, deviceId) {
  const id=clean(requestId,160);
  if(!/^[A-Za-z0-9_-]{16,160}$/.test(id))throw apiError('INVALID_REQUEST_ID','Request ID ไม่ถูกต้อง');
  return transaction(async connection=>{
    const[insert]=await connection.execute("INSERT IGNORE INTO mutation_log (mutation_id,action,actor,status,result_json,created_at) VALUES (?,?,?,'PROCESSING',NULL,?)",[id,action,deviceId,nowSql()]);
    if(insert.affectedRows===1)return{completed:false};
    const[rows]=await connection.execute('SELECT * FROM mutation_log WHERE mutation_id=? FOR UPDATE',[id]);const row=rows[0];
    if(row?.status==='SUCCEEDED'&&row.result_json)return{completed:true,data:JSON.parse(row.result_json)};
    const age=Date.now()-new Date(String(row?.created_at).replace(' ','T')+'Z').getTime();
    if(row?.status==='PROCESSING'&&age<8*60*1000)throw apiError('MUTATION_IN_PROGRESS','รายการเดิมกำลังประมวลผล กรุณารอสักครู่แล้วลองอีกครั้ง',409);
    await connection.execute("UPDATE mutation_log SET action=?,actor=?,status='PROCESSING',result_json=NULL,created_at=?,completed_at=NULL WHERE mutation_id=?",[action,deviceId,nowSql(),id]);
    return{completed:false};
  });
}

async function finishMutation(requestId,data){await execute("UPDATE mutation_log SET status='SUCCEEDED',result_json=:result,completed_at=:completed WHERE mutation_id=:id",{id:requestId,result:JSON.stringify(data),completed:nowSql()});}
async function failMutation(requestId,error){await execute("UPDATE mutation_log SET status='FAILED',result_json=:result,completed_at=:completed WHERE mutation_id=:id",{id:requestId,result:JSON.stringify({message:clean(error.message,500)}),completed:nowSql()});}

async function createExportTicket(buffer,fileName,mimeType,count,metadata,deviceId){const stored=await storeBuffer('exports',fileName,buffer);const downloadToken=token(48),expires=new Date(Date.now()+6*60*60*1000);await execute('INSERT INTO export_tickets (ticket,file_path,file_name,mime_type,size_bytes,device_id,expires_at,created_at) VALUES (:ticket,:path,:name,:mime,:size,:device,:expires,:created)',{ticket:downloadToken,path:stored.relative,name:fileName,mime:mimeType,size:buffer.length,device:deviceId,expires,created:nowSql()});if(metadata?.format){const rows=metadata.rows||[],payload=metadata.payload||{};await execute('INSERT INTO generated_documents (generated_id,format,template_id,group_ids,registration_ids,person_count,file_path,file_name,created_by,created_at) VALUES (:id,:format,:template,:groups,:registrations,:count,:path,:name,:actor,:created)',{id:uuid(),format:metadata.format,template:metadata.templateId||'',groups:JSON.stringify(payload.group_ids||[]),registrations:JSON.stringify(rows.map(row=>row.registration_id)),count:rows.length,path:stored.relative,name:fileName,actor:clean(payload.created_by||'WEB',160),created:nowSql()});}return{fileId:'',fileName,mimeType,count:Number(count)||0,sizeBytes:buffer.length,downloadToken,driveUrl:'',delivery:'chunked'};}

async function getExportFileChunk(downloadToken,offset,deviceId){const ticketValue=clean(downloadToken,96);if(!/^[A-Za-z0-9_-]{40,96}$/.test(ticketValue))throw apiError('INVALID_DOWNLOAD_TOKEN','รหัสดาวน์โหลดไม่ถูกต้อง');const ticketRow=await one('SELECT * FROM export_tickets WHERE ticket=:ticket AND device_id=:device',{ticket:ticketValue,device:deviceId});if(!ticketRow||new Date(String(ticketRow.expires_at).replace(' ','T')+'Z').getTime()<=Date.now())throw apiError('DOWNLOAD_EXPIRED','ลิงก์ดาวน์โหลดหมดอายุ กรุณาสร้างไฟล์ใหม่',410);const start=Math.trunc(Number(offset)||0),size=Number(ticketRow.size_bytes);if(start<0||start>size)throw apiError('INVALID_OFFSET','ตำแหน่งข้อมูลดาวน์โหลดไม่ถูกต้อง');if(start===size)return{offset:start,nextOffset:start,totalBytes:size,base64:'',done:true};const buffer=await readBuffer(ticketRow.file_path),end=Math.min(size,start+1024*1024),chunk=buffer.subarray(start,end);return{offset:start,nextOffset:end,totalBytes:size,base64:chunk.toString('base64'),done:end>=size};}

async function getSystemStatus(){const database=await ping();const lineConfigured=!!(config.lineChannelSecret&&config.lineChannelAccessToken&&config.publicBaseUrl);return{spreadsheet:`MariaDB ${database.version}`,folder:config.dataDir,folderUrl:'',geminiConfigured:!!config.geminiApiKey,lineConfigured,model:config.geminiModel,version:config.appVersion,frontendUrl:config.publicBaseUrl,lineDiagnostics:{webhook:{endpoint:config.publicBaseUrl?`${config.publicBaseUrl}/webhook/line`:''},liff_url:'',android_external_url:config.publicBaseUrl,rich_menus:[],warnings:lineConfigured?[]:['กรุณาตั้งค่า PUBLIC_BASE_URL, LINE_CHANNEL_SECRET และ LINE_CHANNEL_ACCESS_TOKEN บน NAS']},geminiDiagnostics:{message:config.geminiApiKey?'ตั้งค่าแล้ว (ใช้เฉพาะส่วนบิล)':'ยังไม่ได้ตั้งค่า GEMINI_API_KEY',valid:!!config.geminiApiKey},storage:{provider:'Synology NAS',dataDir:config.dataDir},database:{name:database.database_name,version:database.version}};}

async function actionHandler(action,args,session){const createTicket=(buffer,fileName,mimeType,count,metadata)=>createExportTicket(buffer,fileName,mimeType,count,metadata,session.deviceId);const handlers={
  getBootstrapData:()=>masters.getBootstrapData(args[0]),getDashboard:()=>masters.getDashboard(args[0]),listBills:()=>masters.listBills(args[0]),listPendingReviewBills:()=>masters.listPendingReviewBills(),getQuickSettings:()=>masters.getQuickSettings(),saveQuickSettings:()=>masters.saveQuickSettings(args[0]),clearQuickSettings:()=>masters.clearQuickSettings(args[0]),saveMasterData:()=>masters.saveMasterData(args[0],args[1],session.deviceId),deleteMasterData:()=>masters.deleteMasterData(args[0],args[1],session.deviceId),
  submitBillPages:()=>bills.submitBillPages(args[0]),getBillDetail:()=>bills.getBillDetail(args[0]),getBillDocumentPreview:()=>bills.getBillDocumentPreview(args[0]),updateBill:()=>bills.updateBill(args[0],session.deviceId),confirmBill:()=>bills.confirmBill(args[0],args[1]||session.deviceId),deleteBill:()=>bills.deleteBill(args[0],args[1]||session.deviceId),restoreBill:()=>bills.restoreBill(args[0],args[1]||session.deviceId),exportMonthlyBillWord:()=>bills.exportMonthlyBillWord(args[0],createTicket),exportMonthlyBillExcel:()=>bills.exportMonthlyBillExcel(args[0],createTicket),backfillLineUsernames:()=>line.backfillLineUsernames(),
  getReceiptWorkspace:()=>receipts.getReceiptWorkspace(args[0]),saveReceiptTemplate:()=>receipts.saveReceiptTemplate(args[0]),saveLaborGroup:()=>receipts.saveLaborGroup(args[0]),createReceiptBatch:()=>receipts.createReceiptBatch(args[0]),saveReceiptCardDraft:()=>receipts.saveReceiptCardDraft(args[0]),saveReceiptRegistrations:()=>receipts.saveReceiptRegistrations(args[0]),listReceiptRegistrations:()=>receipts.listReceiptRegistrations(args[0]),previewReceiptExport:()=>receipts.previewReceiptExport(args[0]),exportReceiptDocuments:()=>receipts.exportReceiptDocuments(args[0],createTicket),exportReceiptRosterExcel:()=>receipts.exportReceiptRosterExcel(args[0],createTicket),
  getExportFileChunk:()=>getExportFileChunk(args[0],args[1],session.deviceId),getSystemStatus:()=>getSystemStatus(),verifyDatabaseAccess:()=>({url:config.databaseAdminUrl||'#',provider:'MariaDB',message:config.databaseAdminUrl?'เปิด phpMyAdmin':'ไม่ได้เปิดเผย phpMyAdmin จาก WorkHub เพื่อความปลอดภัย'}),
};if(!handlers[action])throw apiError('ACTION_NOT_ALLOWED','คำสั่งนี้ไม่ได้รับอนุญาต',404);return handlers[action]();}

export async function handleApi(body={}){const requestId=clean(body.requestId,160)||uuid();if(clean(body.apiVersion,20)!==config.apiVersion)throw apiError('API_VERSION_MISMATCH','เวอร์ชันหน้าเว็บไม่ตรงกับ Backend กรุณารีโหลด');const action=clean(body.action,80),args=Array.isArray(body.args)?body.args:[];if(action==='health')return envelope(true,{appName:config.appName,appVersion:config.appVersion,apiVersion:config.apiVersion,schemaVersion:config.schemaVersion,serverTime:new Date().toISOString(),accessMode:'OPEN',loginRequired:false,sessionRequired:false,pinMustChange:false,liffId:'',frontendUrl:'',protectedAccess:{configured:!!config.passwordHash,sessionSeconds:config.protectedSessionSeconds},modules:{expenses:true,receipts:!!config.passwordHash,payroll:false,tasks:false}},null,requestId,config.apiVersion);if(action==='openSession')return envelope(true,await openApiSession(args[0]),null,requestId,config.apiVersion);const session=await requireApiSession(body.sessionToken);if(action==='openProtectedSession')return envelope(true,await openProtectedSession(args[0],session.deviceId),null,requestId,config.apiVersion);if(protectedActions.has(action))await requireProtectedSession(body.protectedToken,session.deviceId);const mutation=mutationActions.has(action);if(mutation){const reservation=await reserveMutation(requestId,action,session.deviceId);if(reservation.completed)return envelope(true,reservation.data,null,requestId,config.apiVersion);}try{const data=await actionHandler(action,args,session);if(mutation)await finishMutation(requestId,data);return envelope(true,data,null,requestId,config.apiVersion);}catch(error){if(mutation)await failMutation(requestId,error);throw error;}}

export function apiErrorEnvelope(error,requestId){return envelope(false,null,{code:clean(error.code||'SERVER_ERROR',80),message:clean(error.message||error,500)},requestId,config.apiVersion);}
