import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { config } from '../config.mjs';
import { execute, one, select, transaction } from '../db.mjs';
import { parseDataUrl, readBuffer, removeFile, safeName, storeBuffer, storeCompressedImage } from '../files.mjs';
import { createReceiptDocx, createXlsx, DOCX_MIME, inspectTemplate, XLSX_MIME } from '../exports.mjs';
import { apiError, bool, clean, maskNationalId, normalizeNationalId, nowSql, number, publicRow, uuid } from '../utils.mjs';

const run = promisify(execFile);

function splitName(value) {
  const parts = clean(value, 255).replace(/^(นาย|นางสาว|นาง|เด็กชาย|เด็กหญิง)\s*/, '').replace(/\s+/g, ' ').split(' ').filter(Boolean);
  return { fullName: parts.join(' '), firstName: parts[0] || '', lastName: parts.slice(1).join(' ') };
}

function validNationalId(value) {
  const id = normalizeNationalId(value);
  if (id.length !== 13) return false;
  const sum = [...id.slice(0, 12)].reduce((total, digit, index) => total + Number(digit) * (13 - index), 0);
  return (11 - (sum % 11)) % 10 === Number(id[12]);
}

async function groupsWithProjects() {
  return (await select('SELECT g.*, COALESCE(p.project_name,\'\') AS site_name FROM labor_groups g LEFT JOIN projects p ON p.project_id=g.project_id WHERE g.active=1 ORDER BY g.group_name')).map(publicRow);
}

function registrationForClient(row, includeSensitive = false) {
  const result = publicRow(row);
  result.ocr_warnings = Array.isArray(result.ocr_warnings) ? result.ocr_warnings.join(' | ') : clean(result.ocr_warnings, 1500);
  result.national_id_masked = maskNationalId(result.national_id);
  if (!includeSensitive && result.status !== 'OCR_READY') delete result.card_path;
  return result;
}

export async function listReceiptRegistrations(filters = {}) {
  const where = []; const params = {};
  const ids = Array.isArray(filters.group_ids) ? filters.group_ids.map(value=>clean(value,64)).filter(Boolean) : filters.group_id ? [clean(filters.group_id,64)] : [];
  if (ids.length) { where.push(`group_id IN (${ids.map((_,index)=>`:group${index}`).join(',')})`); ids.forEach((id,index)=>{params[`group${index}`]=id;}); }
  if (filters.status) { where.push('status=:status'); params.status=clean(filters.status,32); }
  if (filters.search) { where.push("LOWER(CONCAT_WS(' ',full_name,national_id,address)) LIKE :search"); params.search=`%${clean(filters.search,180).toLowerCase()}%`; }
  const rows=await select(`SELECT * FROM receipt_registrations ${where.length?`WHERE ${where.join(' AND ')}`:''} ORDER BY updated_at DESC LIMIT 500`,params);
  return { rows:rows.map(row=>registrationForClient(row)), total:rows.length };
}

export async function getReceiptWorkspace(filters = {}) {
  const [templates,groups,projects,registrations]=await Promise.all([select('SELECT template_id,template_name,source_format,page_count,placeholders,active,created_at,updated_at FROM receipt_templates WHERE active=1 ORDER BY updated_at DESC'),groupsWithProjects(),select('SELECT * FROM projects WHERE active=1 ORDER BY project_name'),listReceiptRegistrations(filters)]);
  return { enabled:!!config.passwordHash, securityMessage:config.passwordHash?'':'ผู้ดูแลยังไม่ได้ตั้งรหัสผ่าน WorkHub', templates:templates.map(publicRow), groups, projects:projects.map(publicRow), registrations };
}

export async function saveLaborGroup(payload={}) {
  const name=clean(payload.group_name,255); const type=clean(payload.group_type,80).toUpperCase(); const projectId=clean(payload.project_id,64);
  if(!name)throw apiError('GROUP_NAME_REQUIRED','กรุณาระบุชื่อกลุ่มแรงงาน');if(!['PERMANENT','SITE','OTHER'].includes(type))throw apiError('INVALID_GROUP_TYPE','ประเภทกลุ่มแรงงานไม่ถูกต้อง');if(type==='SITE'&&!await one('SELECT project_id FROM projects WHERE project_id=:id AND active=1',{id:projectId}))throw apiError('PROJECT_REQUIRED','กลุ่มไซต์งานต้องเลือกโครงการ');
  const existing=await one('SELECT group_id FROM labor_groups WHERE active=1 AND LOWER(group_name)=LOWER(:name) AND group_id<>:id',{name,id:clean(payload.group_id,64)});if(existing)throw apiError('DUPLICATE_GROUP','มีชื่อกลุ่มนี้แล้ว');
  const id=clean(payload.group_id,64)||uuid(); const timestamp=nowSql();
  await execute('INSERT INTO labor_groups (group_id,group_name,group_type,project_id,active,created_at,updated_at) VALUES (:id,:name,:type,:project,1,:created,:updated) ON DUPLICATE KEY UPDATE group_name=VALUES(group_name),group_type=VALUES(group_type),project_id=VALUES(project_id),active=1,updated_at=VALUES(updated_at)',{id,name,type,project:type==='SITE'?projectId:'',created:timestamp,updated:timestamp});
  return publicRow(await one('SELECT g.*,COALESCE(p.project_name,\'\') AS site_name FROM labor_groups g LEFT JOIN projects p ON p.project_id=g.project_id WHERE g.group_id=:id',{id}));
}

async function convertDoc(buffer,fileName){const directory=await fs.mkdtemp(path.join(os.tmpdir(),'workhub-doc-'));try{const input=path.join(directory,safeName(fileName,'template.doc'));await fs.writeFile(input,buffer);await run('libreoffice',['--headless','--convert-to','docx','--outdir',directory,input],{timeout:120000,maxBuffer:1024*1024});const output=path.join(directory,path.basename(input).replace(/\.doc$/i,'.docx'));return await fs.readFile(output);}catch(error){throw apiError('DOC_CONVERSION_FAILED',`แปลงไฟล์ DOC ไม่สำเร็จ: ${clean(error.message,300)}`);}finally{await fs.rm(directory,{recursive:true,force:true});}}

export async function saveReceiptTemplate(payload={}) {
  const fileName=safeName(payload.file_name,'template.docx'); const extension=path.extname(fileName).toLowerCase(); const name=clean(payload.template_name||fileName.replace(/\.docx?$/i,''),255);
  if(!['.doc','.docx'].includes(extension))throw apiError('TEMPLATE_FORMAT','รองรับ Template เฉพาะไฟล์ DOC และ DOCX');
  const parsed=parseDataUrl(payload.data_url,['application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/octet-stream']);if(parsed.buffer.length>8*1024*1024)throw apiError('TEMPLATE_TOO_LARGE','Template ต้องมีขนาดไม่เกิน 8 MB');
  const source=await storeBuffer('templates',fileName,parsed.buffer);let normalized=null;
  try{const docx=extension==='.doc'?await convertDoc(parsed.buffer,fileName):parsed.buffer;const validation=await inspectTemplate(docx);normalized=await storeBuffer('templates',`${name}-normalized.docx`,docx);const id=uuid();const timestamp=nowSql();await execute('INSERT INTO receipt_templates (template_id,template_name,source_path,normalized_path,source_format,page_count,placeholders,active,created_at,updated_at) VALUES (:id,:name,:source,:normalized,:format,:pages,:holders,1,:created,:updated)',{id,name,source:source.relative,normalized:normalized.relative,format:extension.slice(1).toUpperCase(),pages:validation.pageCount,holders:JSON.stringify(validation.placeholders),created:timestamp,updated:timestamp});return publicRow(await one('SELECT template_id,template_name,source_format,page_count,placeholders,active,created_at,updated_at FROM receipt_templates WHERE template_id=:id',{id}));}catch(error){await removeFile(source.relative);if(normalized)await removeFile(normalized.relative);throw error;}
}

export async function createReceiptBatch(payload={}){const templateId=clean(payload.template_id,64),groupId=clean(payload.group_id,64),total=Math.trunc(number(payload.total_count));if(!await one('SELECT template_id FROM receipt_templates WHERE template_id=:id AND active=1',{id:templateId}))throw apiError('TEMPLATE_REQUIRED','กรุณาเลือก Template');if(!await one('SELECT group_id FROM labor_groups WHERE group_id=:id AND active=1',{id:groupId}))throw apiError('GROUP_REQUIRED','กรุณาเลือกกลุ่มแรงงาน');if(total<1||total>config.receiptMaxBatchCards)throw apiError('BATCH_SIZE',`อัปโหลดได้ครั้งละ 1-${config.receiptMaxBatchCards} รูป`);const id=uuid(),timestamp=nowSql();await execute('INSERT INTO receipt_batches (batch_id,template_id,group_id,status,total_count,processed_count,error_count,created_by,created_at,updated_at) VALUES (:id,:template,:groupId,\'PROCESSING\',:total,0,0,:actor,:created,:updated)',{id,template:templateId,groupId,total,actor:clean(payload.created_by||'WEB',160),created:timestamp,updated:timestamp});return publicRow(await one('SELECT * FROM receipt_batches WHERE batch_id=:id',{id}));}

async function findDuplicate(nationalId,digest,exclude=''){return one("SELECT registration_id,worker_id,CASE WHEN national_id=:national AND :national<>'' THEN 'NATIONAL_ID' WHEN card_sha256=:digest THEN 'IMAGE' ELSE 'NAME' END AS duplicate_type FROM receipt_registrations WHERE registration_id<>:exclude AND status<>'REJECTED' AND ((national_id=:national AND :national<>'') OR card_sha256=:digest) ORDER BY updated_at DESC LIMIT 1",{national:nationalId,digest,exclude});}

export async function saveReceiptCardDraft(payload={}){const batch=await one('SELECT * FROM receipt_batches WHERE batch_id=:id',{id:clean(payload.batch_id,64)});if(!batch)throw apiError('BATCH_NOT_FOUND','ไม่พบชุดอัปโหลด');let stored;try{stored=await storeCompressedImage('receipt-cards',payload.file_name||'id-card.jpg',payload.data_url,{maxLongEdge:1600,quality:78});const input=payload.ocr&&typeof payload.ocr==='object'?payload.ocr:{};const names=splitName(input.full_name);const national=normalizeNationalId(input.national_id);const address=clean(input.address,1000).replace(/\s+/g,' ');const warnings=(Array.isArray(input.warnings)?input.warnings:[]).map(item=>clean(item,180)).filter(Boolean);if(national&&!validNationalId(national))warnings.push('เลขบัตรไม่ผ่าน checksum กรุณาตรวจสอบ');if(!names.fullName||!national||!address)warnings.push('OCR อ่านข้อมูลไม่ครบ กรุณาตรวจสอบและแก้ไขก่อนบันทึก');const duplicate=await findDuplicate(national,stored.sha256);const id=uuid(),timestamp=nowSql();await execute('INSERT INTO receipt_registrations (registration_id,batch_id,worker_id,template_id,group_id,full_name,first_name,last_name,national_id,address,card_path,card_file_name,card_sha256,card_size_bytes,ocr_confidence,ocr_warnings,duplicate_type,duplicate_of,status,created_at,updated_at) VALUES (:id,:batch,\'\',:template,:groupId,:fullName,:firstName,:lastName,:national,:address,:path,:fileName,:sha,:size,:confidence,:warnings,:duplicateType,:duplicateOf,\'OCR_READY\',:created,:updated)',{id,batch:batch.batch_id,template:batch.template_id,groupId:batch.group_id,...names,national,address,path:stored.relative,fileName:stored.relative.split('/').pop(),sha:stored.sha256,size:stored.size,confidence:Math.max(0,Math.min(100,number(input.confidence))),warnings:JSON.stringify([...new Set(warnings)]),duplicateType:duplicate?.duplicate_type||'',duplicateOf:duplicate?.registration_id||'',created:timestamp,updated:timestamp});await execute('UPDATE receipt_batches SET processed_count=processed_count+1,updated_at=:updated WHERE batch_id=:id',{id:batch.batch_id,updated:timestamp});return registrationForClient(await one('SELECT * FROM receipt_registrations WHERE registration_id=:id',{id}),true);}catch(error){if(stored)await removeFile(stored.relative);await execute('UPDATE receipt_batches SET error_count=error_count+1,updated_at=:updated WHERE batch_id=:id',{id:batch.batch_id,updated:nowSql()});throw error;}}

export async function saveReceiptRegistrations(payload={}){const batchId=clean(payload.batch_id,64),inputs=Array.isArray(payload.rows)?payload.rows:[];if(!batchId||!inputs.length)throw apiError('REGISTRATIONS_REQUIRED','ไม่พบรายการที่ต้องการบันทึก');if(inputs.length>config.receiptMaxBatchCards)throw apiError('BATCH_SIZE','จำนวนรายการเกินขีดจำกัด');return transaction(async connection=>{const saved=[];for(const input of inputs){const id=clean(input.registration_id,64);const[currentRows]=await connection.execute('SELECT * FROM receipt_registrations WHERE registration_id=? AND batch_id=? FOR UPDATE',[id,batchId]);const current=currentRows[0];if(!current)throw apiError('REGISTRATION_NOT_FOUND','ไม่พบรายการ OCR ที่ต้องการบันทึก');const names=splitName(input.full_name),national=normalizeNationalId(input.national_id),address=clean(input.address,1000).replace(/\s+/g,' ');if(!names.fullName||!national||!address)throw apiError('REQUIRED_FIELDS','กรุณากรอกชื่อ เลขบัตร และที่อยู่ให้ครบ');if(!validNationalId(national))throw apiError('INVALID_NATIONAL_ID',`เลขบัตรประชาชนของ ${names.fullName} ไม่ถูกต้อง`);const duplicate=await findDuplicate(national,current.card_sha256,id);if(duplicate&&!bool(input.allow_existing_worker))throw apiError('DUPLICATE_REGISTRATION',`${names.fullName} มีข้อมูลซ้ำ กรุณาเลือกเชื่อมกับบุคคลเดิม`);const timestamp=nowSql();let workerId=duplicate?.worker_id||'';if(!workerId){const[workerRows]=await connection.execute('SELECT worker_id FROM workers WHERE national_id=? LIMIT 1 FOR UPDATE',[national]);workerId=workerRows[0]?.worker_id||uuid();}await connection.execute('INSERT INTO workers (worker_id,full_name,first_name,last_name,national_id,address,status,created_at,updated_at) VALUES (?,?,?,?,?,?,\'ACTIVE\',?,?) ON DUPLICATE KEY UPDATE full_name=VALUES(full_name),first_name=VALUES(first_name),last_name=VALUES(last_name),address=VALUES(address),status=\'ACTIVE\',updated_at=VALUES(updated_at)',[workerId,names.fullName,names.firstName,names.lastName,national,address,timestamp,timestamp]);const membershipId=uuid();await connection.execute('INSERT INTO worker_group_members (membership_id,worker_id,group_id,active,created_at,updated_at) VALUES (?,?,?,1,?,?) ON DUPLICATE KEY UPDATE active=1,updated_at=VALUES(updated_at)',[membershipId,workerId,current.group_id,timestamp,timestamp]);await connection.execute('UPDATE receipt_registrations SET worker_id=?,full_name=?,first_name=?,last_name=?,national_id=?,address=?,duplicate_type=?,duplicate_of=?,status=\'SAVED\',updated_at=? WHERE registration_id=?',[workerId,names.fullName,names.firstName,names.lastName,national,address,duplicate?.duplicate_type||'',duplicate?.registration_id||'',timestamp,id]);const[rows]=await connection.execute('SELECT * FROM receipt_registrations WHERE registration_id=?',[id]);saved.push(registrationForClient(rows[0]));}await connection.execute('UPDATE receipt_batches SET status=\'COMPLETED\',updated_at=? WHERE batch_id=?',[nowSql(),batchId]);return{saved,count:saved.length};});}

async function resolveSelection(payload,max){const ids=Array.isArray(payload.registration_ids)?payload.registration_ids.map(value=>clean(value,64)).filter(Boolean):[];const groups=Array.isArray(payload.group_ids)?payload.group_ids.map(value=>clean(value,64)).filter(Boolean):[];if(!ids.length&&!groups.length)throw apiError('EXPORT_SELECTION_REQUIRED','กรุณาเลือกรายชื่อหรือกลุ่มที่ต้องการ Export');const params={};let condition;if(ids.length){condition=`registration_id IN (${ids.map((id,index)=>{params[`id${index}`]=id;return`:id${index}`;}).join(',')})`;}else{condition=`group_id IN (${groups.map((id,index)=>{params[`group${index}`]=id;return`:group${index}`;}).join(',')})`;}const rows=await select(`SELECT * FROM receipt_registrations WHERE status='SAVED' AND ${condition} ORDER BY group_id,full_name`,params);if(!rows.length)throw apiError('EXPORT_EMPTY','ไม่พบรายชื่อที่พร้อม Export');if(rows.length>max)throw apiError('EXPORT_LIMIT',`Export ได้สูงสุด ${max} คนต่อครั้ง`);return rows;}

export async function previewReceiptExport(payload={}){const rows=await resolveSelection(payload,5000),groups=await groupsWithProjects(),map=new Map(groups.map(group=>[group.group_id,group])),grouped=new Map();for(const row of rows){const group=map.get(row.group_id)||{group_id:row.group_id,group_name:'ไม่ระบุกลุ่ม',site_name:''};const item=grouped.get(group.group_id)||{group_id:group.group_id,group_name:group.group_name,site_name:group.site_name||'',people:[]};item.people.push({registration_id:row.registration_id,full_name:row.full_name,national_id_masked:maskNationalId(row.national_id)});grouped.set(group.group_id,item);}return{total:rows.length,groups:[...grouped.values()]};}

export async function exportReceiptRosterExcel(payload,createTicket){const rows=await resolveSelection(payload,5000),groups=await groupsWithProjects(),map=new Map(groups.map(group=>[group.group_id,group]));const values=rows.map((row,index)=>{const group=map.get(row.group_id)||{};return[index+1,row.worker_id,row.full_name,row.national_id,row.address,group.group_name||'',group.site_name||'',row.updated_at];});const buffer=await createXlsx('รายชื่อแรงงาน',['ลำดับ','รหัสบุคคล','ชื่อ-นามสกุล','เลขบัตรประชาชน','ที่อยู่','กลุ่มแรงงาน','ไซต์งาน','วันที่บันทึก'],values,[8,24,30,20,55,28,32,24]);return createTicket(buffer,`รายชื่อใบรับเงิน_${new Date().toISOString().slice(0,10)}_${rows.length}คน.xlsx`,XLSX_MIME,rows.length,{format:'XLSX',rows,payload});}

export async function exportReceiptDocuments(payload,createTicket){const rows=await resolveSelection(payload,200),templateId=clean(payload.template_id,64)||rows[0].template_id,template=await one('SELECT * FROM receipt_templates WHERE template_id=:id AND active=1',{id:templateId});if(!template)throw apiError('TEMPLATE_NOT_FOUND','ไม่พบ Template ที่เลือก');if(rows.some(row=>row.template_id!==templateId)&&!bool(payload.force_template))throw apiError('MIXED_TEMPLATES','รายการที่เลือกใช้หลาย Template');const registrations=[];for(const row of rows)registrations.push({...row,cardBuffer:await readBuffer(row.card_path)});const buffer=await createReceiptDocx(await readBuffer(template.normalized_path),registrations);return createTicket(buffer,`ใบรับเงิน_${new Date().toISOString().slice(0,10)}_${rows.length}คน.docx`,DOCX_MIME,rows.length,{format:'DOCX',templateId,rows,payload});}
