ALTER TABLE receipt_batches
  ADD COLUMN IF NOT EXISTS ai_model VARCHAR(120) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS last_error TEXT NULL;

ALTER TABLE receipt_registrations
  ADD COLUMN IF NOT EXISTS ocr_provider VARCHAR(40) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ai_model VARCHAR(120) NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS ai_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ai_last_error TEXT NULL,
  ADD COLUMN IF NOT EXISTS ai_processed_at DATETIME(3) NULL;
