const APP_CONFIG = Object.freeze({
  APP_NAME: 'WorkHub',
  VERSION: '3.1.0',
  API_VERSION: '2.0',
  SCHEMA_VERSION: 3,
  TIME_ZONE: 'Asia/Bangkok',
  ROOT_FOLDER_NAME: 'Line-Expense-App-V2',
  EXPORT_FOLDER_NAME: 'exports',
  EXPORT_CHUNK_BYTES: 1024 * 1024,
  EXPORT_TICKET_SECONDS: 6 * 60 * 60,
  DEFAULT_LIFF_ID: '',
  GEMINI_MODEL: 'gemini-3.5-flash-lite',
  GEMINI_PROMPT_VERSION: 'bill-th-v2',
  MAX_PAGES_PER_BILL: 8,
  MAX_FILE_MB: 8,
  MAX_UPLOAD_TOTAL_MB: 14,
  IMAGE_MAX_LONG_EDGE: 1800,
  IMAGE_TARGET_BYTES: 1200 * 1024,
  IMAGE_JPEG_QUALITY: 0.8,
  RECEIPT_MAX_BATCH_CARDS: 40,
  RECEIPT_MAX_TEMPLATE_MB: 8,
  RECEIPT_MAX_EXPORT_PEOPLE: 200,
  EXPORT_IMAGE_TARGET_BYTES: 900 * 1024,
  SESSION_HOURS: 24,
  API_SESSION_SECONDS: 6 * 60 * 60,
  PROTECTED_SESSION_SECONDS: 6 * 60 * 60,
  PROTECTED_MAX_ATTEMPTS: 5,
  PROTECTED_GLOBAL_MAX_ATTEMPTS: 30,
  PROTECTED_ATTEMPT_WINDOW_SECONDS: 15 * 60,
  PROTECTED_LOCKOUT_SECONDS: 15 * 60,
  PROTECTED_HASH_ROUNDS: 512,
  LOCK_WAIT_MS: 30000,
});

const PROP_KEYS = Object.freeze({
  GEMINI_API_KEY: 'GEMINI_API_KEY',
  LINE_ACCESS_TOKEN: 'LINE_ACCESS_TOKEN',
  LINE_CHANNEL_SECRET: 'LINE_CHANNEL_SECRET',
  LIFF_ID: 'LIFF_ID',
  FRONTEND_URL: 'FRONTEND_URL',
  SPREADSHEET_ID: 'SPREADSHEET_ID',
  API_SESSION_VERSION: 'API_SESSION_VERSION',
  LINE_WEBHOOK_KEY: 'LINE_WEBHOOK_KEY',
  ROOT_FOLDER_ID: 'ROOT_FOLDER_ID',
  TAX_ID_TEXT_MIGRATION: 'TAX_ID_TEXT_MIGRATION_V1',
  QUICK_PAGE_COUNT: 'QUICK_PAGE_COUNT',
  QUICK_PROJECT_ID: 'QUICK_PROJECT_ID',
  QUICK_COMPANY_ID: 'QUICK_COMPANY_ID',
  QUICK2_PAGE_COUNT: 'QUICK2_PAGE_COUNT',
  QUICK2_PROJECT_ID: 'QUICK2_PROJECT_ID',
  QUICK2_COMPANY_ID: 'QUICK2_COMPANY_ID',
  RECEIPT_MODULE_ENABLED: 'RECEIPT_MODULE_ENABLED',
  PROTECTED_PASSWORD_SALT: 'PROTECTED_PASSWORD_SALT',
  PROTECTED_PASSWORD_HASH: 'PROTECTED_PASSWORD_HASH',
  PROTECTED_PASSWORD_HASH_ROUNDS: 'PROTECTED_PASSWORD_HASH_ROUNDS',
  PROTECTED_SESSION_VERSION: 'PROTECTED_SESSION_VERSION',
});

const SHEETS = Object.freeze({
  PROJECTS: 'Projects',
  COMPANIES: 'Companies',
  CATEGORIES: 'Categories',
  VENDORS: 'Vendors',
  BILLS: 'Bills',
  ITEMS: 'BillItems',
  DOCUMENTS: 'BillDocuments',
  SESSIONS: 'UploadSessions',
  AI_USAGE: 'AiUsage',
  AUDIT: 'AuditLogs',
  MUTATIONS: 'MutationLog',
  SECURITY: 'SecurityLog',
  MIGRATIONS: 'SchemaMigrations',
  RECEIPT_TEMPLATES: 'ReceiptTemplates',
  LABOR_GROUPS: 'LaborGroups',
  WORKERS: 'Workers',
  WORKER_GROUP_MEMBERS: 'WorkerGroupMembers',
  RECEIPT_BATCHES: 'ReceiptBatches',
  RECEIPT_REGISTRATIONS: 'ReceiptRegistrations',
  GENERATED_DOCUMENTS: 'GeneratedDocuments',
});

const SHEET_DEFINITIONS = Object.freeze({
  Projects: ['project_id', 'project_code', 'project_name', 'description', 'active', 'created_at', 'updated_at'],
  Companies: ['company_id', 'company_name', 'branch_name', 'tax_id', 'address', 'active', 'created_at', 'updated_at'],
  Categories: ['category_id', 'category_name', 'aliases', 'active', 'created_at', 'updated_at'],
  Vendors: ['vendor_id', 'vendor_name', 'normalized_name', 'tax_id', 'branch_name', 'address', 'use_count', 'last_used_at', 'created_at', 'updated_at'],
  Bills: [
    'bill_id', 'session_id', 'project_id', 'company_id', 'category_id', 'doc_type', 'document_no',
    'document_date', 'due_date', 'vendor_id', 'vendor_name', 'vendor_tax_id', 'vendor_branch', 'vendor_address',
    'buyer_name', 'buyer_tax_id', 'buyer_address', 'currency', 'subtotal', 'discount', 'vat_rate', 'vat_amount',
    'withholding_tax', 'grand_total', 'payment_method', 'description', 'notes', 'page_count', 'image_quality',
    'quality_score', 'needs_review', 'review_reasons', 'company_match', 'tax_id_match', 'duplicate_key',
    'status', 'source', 'source_user_id', 'folder_path', 'created_at', 'updated_at', 'confirmed_at', 'address_match', 'source_context_id'
  ],
  BillItems: ['item_id', 'bill_id', 'line_no', 'description', 'quantity', 'unit', 'unit_price', 'discount', 'vat_amount', 'amount', 'sku'],
  BillDocuments: ['doc_id', 'bill_id', 'session_id', 'page_no', 'file_id', 'file_name', 'mime_type', 'file_url', 'sha256', 'size_bytes', 'created_at', 'original_size_bytes', 'compression', 'width', 'height'],
  UploadSessions: ['session_id', 'project_id', 'company_id', 'expected_pages', 'received_pages', 'status', 'source', 'source_user_id', 'created_at', 'expires_at', 'updated_at', 'source_context_id'],
  AiUsage: ['usage_id', 'bill_id', 'model', 'prompt_version', 'input_tokens', 'output_tokens', 'thought_tokens', 'total_tokens', 'latency_ms', 'success', 'error', 'created_at'],
  AuditLogs: ['log_id', 'entity_type', 'entity_id', 'action', 'actor', 'before_json', 'after_json', 'created_at'],
  MutationLog: ['mutation_id', 'action', 'actor', 'status', 'result_json', 'created_at', 'completed_at'],
  SecurityLog: ['event_id', 'event_type', 'device_id', 'success', 'detail', 'created_at'],
  SchemaMigrations: ['version', 'name', 'applied_at'],
  ReceiptTemplates: ['template_id', 'template_name', 'source_file_id', 'normalized_file_id', 'source_format', 'page_count', 'placeholders', 'active', 'created_at', 'updated_at'],
  LaborGroups: ['group_id', 'group_name', 'group_type', 'project_id', 'active', 'created_at', 'updated_at'],
  Workers: ['worker_id', 'full_name', 'first_name', 'last_name', 'national_id', 'address', 'status', 'created_at', 'updated_at'],
  WorkerGroupMembers: ['membership_id', 'worker_id', 'group_id', 'active', 'created_at', 'updated_at'],
  ReceiptBatches: ['batch_id', 'template_id', 'group_id', 'status', 'total_count', 'processed_count', 'error_count', 'created_by', 'created_at', 'updated_at'],
  ReceiptRegistrations: ['registration_id', 'batch_id', 'worker_id', 'template_id', 'group_id', 'full_name', 'first_name', 'last_name', 'national_id', 'address', 'card_file_id', 'card_file_name', 'card_sha256', 'card_size_bytes', 'ocr_confidence', 'ocr_warnings', 'duplicate_type', 'duplicate_of', 'status', 'created_at', 'updated_at'],
  GeneratedDocuments: ['generated_id', 'format', 'template_id', 'group_ids', 'registration_ids', 'person_count', 'file_id', 'file_name', 'created_by', 'created_at'],
});

const DEFAULT_COMPANIES = Object.freeze([
  {
    company_name: 'บริษัท วิศวกรรมธรณีและฐานราก จำกัด',
    branch_name: 'สำนักงานใหญ่',
    tax_id: '0105536084347',
    address: '151 ถนนนวลจันทร์ แขวงนวลจันทร์ เขตบึงกุ่ม กทม. 10230',
  },
  {
    company_name: 'บริษัท ทีม คอนซัลติ้ง เอนจิเนียริ่ง แอนด์ แมเนจเมนท์ จำกัด (มหาชน)',
    branch_name: 'สำนักงานใหญ่',
    tax_id: '0107561000030',
    address: '151 ถนนนวลจันทร์ แขวงนวลจันทร์ เขตบึงกุ่ม กรุงเทพฯ 10230',
  },
]);

const DEFAULT_CATEGORIES = Object.freeze([
  { category_name: 'ค่าผ่านทาง/ทางด่วน', aliases: 'ค่าทางด่วน,ค่าผ่านทาง,toll,m-pass,easypass' },
  { category_name: 'เอกสารใบส่งของ', aliases: 'ใบส่งของ,delivery note' },
  { category_name: 'การบริการ', aliases: 'ค่าบริการ,service' },
  { category_name: 'วัสดุอุปกรณ์', aliases: 'วัสดุ,อุปกรณ์,เครื่องมือ' },
  { category_name: 'ที่พัก', aliases: 'โรงแรม,ที่พัก,hotel' },
  { category_name: 'อาหาร/เดินทาง', aliases: 'อาหาร,น้ำมัน,แท็กซี่,เดินทาง' },
  { category_name: 'อื่นๆ', aliases: 'อื่นๆ,other' },
]);
